// <auto-generated />
using System;
using System.Collections.Generic;
using Forge.Diet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forge.Diet.Infrastructure.Migrations
{
    [DbContext(typeof(DietDbContext))]
    [Migration("20260819115022_AddDailyGoals")]
    partial class AddDailyGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calories")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Carbohydrates")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Fat")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Fiber")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Protein")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DailyGoals", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyMeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("Date", "MealId")
                        .IsUnique();

                    b.ToTable("DailyMeals", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyMealMealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyMealId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Servings")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DailyMealId");

                    b.HasIndex("MealItemId");

                    b.ToTable("DailyMealMealItems", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("NetWeight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Nutrition", "Forge.Diet.Domain.Entities.Ingredient.Nutrition#Nutrition", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Calories")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Carbohydrates")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Carbohydrates");

                            b1.Property<decimal>("Fat")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Fat");

                            b1.Property<decimal>("Fiber")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Fiber");

                            b1.Property<decimal>("Protein")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("Protein");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NutritionBasis", "Forge.Diet.Domain.Entities.Ingredient.NutritionBasis#NutritionBasis", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("NutritionBasisAmount");

                            b1.Property<Guid>("UnitId")
                                .HasColumnType("uuid")
                                .HasColumnName("NutritionBasisUnitId");
                        });

                    b.HasKey("Id");

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.IngredientConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("TargetUnitId");

                    b.ToTable("IngredientConversions", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Meals", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.MealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MealItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealItemId");

                    b.HasIndex("UnitId");

                    b.ToTable("MealIngredients", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MealItems", (string)null);
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Standard metric gram",
                            IsSystem = true,
                            Name = "Gram"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Standard metric milliliter",
                            IsSystem = true,
                            Name = "Milliliter"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Individual item/serving count",
                            IsSystem = true,
                            Name = "Piece"
                        });
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyMeal", b =>
                {
                    b.HasOne("Forge.Diet.Domain.Entities.Meal", "Meal")
                        .WithMany("DailyMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyMealMealItem", b =>
                {
                    b.HasOne("Forge.Diet.Domain.Entities.DailyMeal", "DailyMeal")
                        .WithMany("MealItems")
                        .HasForeignKey("DailyMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forge.Diet.Domain.Entities.MealItem", "MealItem")
                        .WithMany()
                        .HasForeignKey("MealItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyMeal");

                    b.Navigation("MealItem");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.IngredientConversion", b =>
                {
                    b.HasOne("Forge.Diet.Domain.Entities.Ingredient", null)
                        .WithMany("Conversions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Forge.Diet.Domain.Entities.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("TargetUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.MealIngredient", b =>
                {
                    b.HasOne("Forge.Diet.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Forge.Diet.Domain.Entities.MealItem", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MealItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Forge.Diet.Domain.Entities.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.DailyMeal", b =>
                {
                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Conversions");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.Meal", b =>
                {
                    b.Navigation("DailyMeals");
                });

            modelBuilder.Entity("Forge.Diet.Domain.Entities.MealItem", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
